### ISSUE TITLE
Chart missing nameOverride and fullnameOverride

### ISSUE THREAD

**Issue by marceloapps** [CiscoDevNet/appdynamics-charts#24]
Hi there,

I don't know if this is more of a doubt, but when trying to install the cluster agent chart using terraform, I can't find any option to override its name. So the pod ends up with a very "default" name.

## terraform code
```hcl
resource "helm_release" "appdynamics" {
  name = "k8s"
  namespace = "appdynamics"
  repository = "https://ciscodevnet.github.io/appdynamics-charts"
  chart = "cluster-agent"

  values = [
    file("${path.module}/appdynamics-values.yaml")
  ]
}
```

## values
```yaml
nameOverride: "test"
fullnameOverride: "test"

deploymentMode: PRIMARY

imageInfo:
  agentImage: docker.io/appdynamics/cluster-agent
  agentTag: 20.9.0
  operatorImage: docker.io/appdynamics/cluster-agent-operator
  operatorTag: latest
  imagePullPolicy: IfNotPresent
  machineAgentImage: docker.io/appdynamics/machine-agent-analytics
  machineAgentTag: 21.9.0
  machineAgentWinTag: 21.9.0-win-ltsc2019  

controllerInfo:
  url: https://apm-foobar.pl.appdynamics.com:443
  account: itau-dev                   
  username: FOO
  password: BAR
  accessKey: FOO123BAR456

clusterAgent:
  nsToMonitor: [default,kube-node-lease,kube-public,kube-system,appdynamics]
  clusterMetricsSyncInterval: 60
  metadataSyncInterval: 60
  eventUploadInterval: 10
  httpClientTimeout: 30
  podBatchSize: 6
  imagePullSecret: ""
  containerProperties:
    containerBatchSize: 5
    containerParallelRequestLimit: 1
    containerRegistrationInterval: 120
  logProperties:
    logFileSizeMb: 5
    logFileBackups: 3
    logLevel: INFO
  metricProperties:
    metricsSyncInterval: 30
    metricUploadRetryCount: 2
    metricUploadRetryIntervalMilliSeconds: 5

install:
  metrics-server: true  
```

## pods
```console
$ kubectl get pods -n appdynamics
NAMESPACE       NAME                                             READY   STATUS    RESTARTS   AGE
appdynamics     appdynamics-operator-646866b895-7nqd8            1/1     Running   0          56s
appdynamics     k8s-appdynamics-cluster-agent-84b466c677-v2p4t   1/1     Running   0          50s
appdynamics     k8s-metrics-server-d65b5b4c-wwzzd                1/1     Running   0          56s
```

I wanted to be able to change the cluster agent pod's name. Is that possible?
Tks
