### ISSUE TITLE
infraViz.nodeOS condition not working as intended

### ISSUE THREAD

**Issue by davidbgonz** [CiscoDevNet/appdynamics-charts#25]
Hello,

I am trying to setup the cluster-agent chart on an AKS cluster using both Linux and Windows nodes. The default Linux value for `nodeOS` works just fine. When I try to use any of the other options (windows and all), this is the resulting message: `Error: UPGRADE FAILED: YAML parse error on cluster-agent/templates/infraviz.yaml: error converting YAML to JSON: yaml: line 10: mapping values are not allowed in this context`
Looking at the infraviz template I do not see any glaring issues. I made sure to update the helm repo, and destroy the CRDs before trying again just in case but to no avail. Manually updating the infraviz resource with what the conditional was supposed to output is also working for me. Let me know if there is any information you need for this. Not 100% sure what to provide.

**Comment by davidbgonz** [comment]
I found the issue with that section of the infraviz template.
The section of the infraviz template with the issue:
```yaml
{{ if eq .Values.infraViz.nodeOS "linux" }}
image: {{ .Values.imageInfo.machineAgentImage }}:{{ .Values.imageInfo.machineAgentTag -}}
{{ else if eq .Values.infraViz.nodeOS "windows" }}
imageWin: {{ .Values.imageInfo.machineAgentWinImage }}:{{ .Values.imageInfo.machineAgentWinTag -}}
globalAccount: {{ required "AppDynamics controller global account is required when using machine-agent win image!" .Values.controllerInfo.globalAccount -}}
{{ else if eq .Values.infraViz.nodeOS "all" }}
image: {{ .Values.imageInfo.machineAgentImage }}:{{ .Values.imageInfo.machineAgentTag }}
imageWin: {{ .Values.imageInfo.machineAgentWinImage }}:{{ .Values.imageInfo.machineAgentWinTag -}}
globalAccount: {{ required "AppDynamics controller global account is required when using machine-agent win image!" .Values.controllerInfo.globalAccount -}}
{{- end }}
```
The ending dash to cleanup the whitespace on the imageWin lines throws the globalAccount line up to the same line which creates invalid YAML. The solution is to cleanup the empty lines on the conditional itself:
```yaml
{{- if eq .Values.infraViz.nodeOS "linux" }}
image: {{ .Values.imageInfo.machineAgentImage }}:{{ .Values.imageInfo.machineAgentTag }}
{{- else if eq .Values.infraViz.nodeOS "windows" }}
imageWin: {{ .Values.imageInfo.machineAgentWinImage }}:{{ .Values.imageInfo.machineAgentWinTag }}
globalAccount: {{ required "AppDynamics controller global account is required when using machine-agent win image!" .Values.controllerInfo.globalAccount }}
{{- else if eq .Values.infraViz.nodeOS "all" }}
image: {{ .Values.imageInfo.machineAgentImage }}:{{ .Values.imageInfo.machineAgentTag }}
imageWin: {{ .Values.imageInfo.machineAgentWinImage }}:{{ .Values.imageInfo.machineAgentWinTag }}
globalAccount: {{ required "AppDynamics controller global account is required when using machine-agent win image!" .Values.controllerInfo.globalAccount }}
{{- end }}
```
