### ISSUE TITLE
Use of "latest" and "win-latest" tags in helm charts does not follow best-practice

### ISSUE THREAD

**Issue by technotaff-nbs** [CiscoDevNet/appdynamics-charts#34]
We are a large AppD customer, looking to expand our use of the cluster-agent.

Currently we have to patch our values file with replacements for "latest" and "win-latest". It is not helm-chart and/or kubernetes best-practice to use floating image versions.

References to "latest" and "win-latest" should be updated to the current release when the helm chart is released.

This was the helm chart footprint is known and tests. We test and whitelist all images which are pulled to our clusters, use of non version-aligned tags breaks this pattern.

instead of
```
imageInfo:
  agentImage: docker.io/appdynamics/cluster-agent
  agentTag: 22.9.0
  operatorImage: docker.io/appdynamics/cluster-agent-operator
  operatorTag: 22.9.0
  imagePullPolicy: Always                               # Will be used for operator pod
  machineAgentImage: docker.io/appdynamics/machine-agent
  machineAgentTag: latest
  machineAgentWinImage: docker.io/appdynamics/machine-agent-analytics
  machineAgentWinTag: win-latest
  netVizImage: docker.io/appdynamics/machine-agent-netviz
  netvizTag: latest
```

it would be better to have a tested version of machineAgentTag, machineAgentWinTag and netvizTag:

```
imageInfo:
  agentImage: docker.io/appdynamics/cluster-agent
  agentTag: 22.9.0
  operatorImage: docker.io/appdynamics/cluster-agent-operator
  operatorTag: 22.9.0
  imagePullPolicy: Always                               # Will be used for operator pod
  machineAgentImage: docker.io/appdynamics/machine-agent
  machineAgentTag: 22.9.0
  machineAgentWinImage: docker.io/appdynamics/machine-agent-analytics
  machineAgentWinTag: 22.9.0
  netVizImage: docker.io/appdynamics/machine-agent-netviz
  netvizTag: 21.3.0
```
